### ISSUE TITLE
感谢大佬，请问有其它参数吗？

### ISSUE THREAD

**Issue by yeyuchen198** [dev-coco/Facebook-API-Params-Generator#1]
data = {
    'av': '0',
    '__user': '0',
    '__a': '1',
    '__req': '10',
    '__hs': '19664.HYP:comet_pkg.2.1..2.1',
    'dpr': '1.5',
    '__ccg': 'EXCELLENT',
    '__rev': '1009667778',
    '__s': 'qx9c2j:1gh44p:1hbp4t',
    '__hsi': '7297116708979600528',
    '__dyn': '7AzHK4HzEmgDx-5Q1ryaxG4QjFwLBwopU98nwgUao4ubyQdwSAxacyU8EW1twYwJyEiwsobo5a58e8hw8u5UB0n82nwb-q7oc81xoszUsK1Rwwwg8a8465o-cw8a1TwgEcEhwGxu782lwj8bU9kbxS210hUb82kwiE567Udo5qfK0zEkxe2GexeeDwkUtxGm2SUbElxm3y3aexfxmu3W3rwxwhFVovUy2a0SEuBwFKq2-azqwqo4i223908O3216xi4UdUcojxK2B0LwNwJwxyo566k1FwgU4q3G3Wfw',
    '__csr': 'gcY5kAB9Tl88il4lf9YYnbYBOPikARWOt998GXOmWy78JHEFKznO9aIBp4ARHKahbH-HLhbSrBl9eCJfhYxUyFVmrFBzrVXDKuaumFaLARhLmpGVK-CFElzpp4mbQiAVaqAKrQ8Axby9EptykiWK7e8ye8zkbyk6HKbzQ4GByUsBz8tUvCVECGmim4oK5pEmximEWGzWCCWyWzEkx62129Aq9CyXBBzoiypby8y8x2i7WGbwTgqzEOcglwLyaxe4E8uU9ofVELmum44cDx2VkmFogz8gwLwm98a-czF8pzFUb8tykqqm68SEKmdz-ezqxbDxa3qUFwhqAxu5-1zBggx3wTUWEKp121AwVwGzoC1lwh4GwxggFo7KhTG9k9WeDkEC4NIR8s1bxe1oxC3udwGx4w2sg522648aoyttQGg4y0Z8dE3sxDwkod8xxl0jUnwvo5dwgaxt7h9FUG1wxq3ucm1exu2CUjyUiwko0Ey4DgO2C2F1yU08A82kG4o-0v2m08Zw68g0CS0cCCw5kxi0bHw0sV80dIU6y1Yw4Cwsqw67xe0eKwFg7i0WE17811o1mE2ywbC0H81bof84mdw911m17g3Yw6Cu0huhw2So0Su0MU0gfKuFU0RK0rSd80auw3no8E0jpiwhei02my0Qo6e0g6hQ0c9wokdx5076yUswno1pe360S88A2mdg1AA0S66sTyU',
    '__comet_req': '15',
    'fb_dtsg': 'NAcNceZn5xWhvsERO3IeQrBeg86-Wi_WxoAK6nHpMDD8YAJSVSkKKzw:24:1695631985',
    'jazoest': '25483',
    'lsd': 'CbHiGOc2GlEFSeDla5FD-8',
    '__aaid': '0',
    '__spin_r': '1009667778',
    '__spin_b': 'trunk',
    '__spin_t': '1698992380',
    'fb_api_caller_class': 'RelayModern',
    'fb_api_req_friendly_name': 'CometUFICommentsProviderForDisplayCommentsQuery',
    'variables': '{"UFI2CommentsProvider_commentsKey":"CometVideoHomeNewPermalinkHeroUnitQuery","__false":false,"__true":true,"after":null,"before":null,"displayCommentsContextEnableComment":null,"displayCommentsContextIsAdPreview":null,"displayCommentsContextIsAggregatedShare":null,"displayCommentsContextIsStorySet":null,"displayCommentsFeedbackContext":null,"feedLocation":"TAHOE","feedbackSource":41,"first":null,"focusCommentID":null,"includeHighlightedComments":false,"includeNestedComments":true,"initialViewOption":null,"isInitialFetch":false,"isPaginating":false,"last":null,"scale":1.5,"topLevelViewOption":"RECENT_ACTIVITY","useDefaultActor":false,"viewOption":"RECENT_ACTIVITY","id":"ZmVlZGJhY2s6NjgxNjc0MjAyMDIxMTk1"}',
    'server_timestamps': 'true',
    'doc_id': '6599866996797413',
}

这些参数都有吗

**Comment by dev-coco** [comment]
没有，这个项目只针对dyn参数

**Comment by yeyuchen198** [comment]
> 没有，这个项目只针对dyn参数

恩，我现在就缺一个__csr参数🤔

**Comment by dev-coco** [comment]
__csr在模块里面可以取到
